### ISSUE TITLE
Issue in data generation

### ISSUE THREAD

**Issue by ieea** [donalee/taxocom#1]
Hi,
I followed the steps suggested in readme file specific to "data", the code runs well and all the files are generated in the input folder but with very limited or no data.
Please help with detailed steps to create docs.txt & terms.txt as they have been used as an input. 
Thanks in advance!! Please help.
Regards,
Gaurav

**Comment by donalee** [comment]
Hi, 
Given the limited information about your problem, one possible issue is that only a few terms (terms.txt) appear in your corpus (docs.txt) frequently enough to learn their embeddings. Could you check your docs.txt and terms.txt first? You can lower the value of "min_count" variable in the C source code for embedding (i.e., jose.c and josd.c). Their default value is 5, so all the terms that appear in the corpus less than 5 times will be filtered out.

**Comment by ieea** [comment]
Thanks!! issue is resolved
